baseurl = "https://kidimproved.github.io/"
languageCode = "en-us"
title = "Kid ImprovEd"
canonifyurls = true

[params]

  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more informtion take a look at the README.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Kid ImprovEd"
  description = "A non-profit dedicated to teaching improv skills to K-12 students."

  # The path must be relative to the static folder
  favicon = "favicon.ico"


  # Navigation
  [params.navigation]
    brand = "Kid ImprovEd"

    [params.navigation.links]
      about     = "Mission"
      services  = "Team"
      portfolio = "Portfolio"
      contact   = "Contact"


  # Hero section
  [params.hero]
    # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
    slogan     = "Your awesome slogan"
    subtitle   = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis nesciunt consequatur ut nihil voluptatem fugiat eos eveniet alias in veniam?"
    buttonText = "Find out more"


  # About section
  [params.about]
    headline    = "Our mission"
    description = "To foster children's confidence, creativity, and collaboration skills through improvisation for long term growth and development."
    buttonText  = "Get started!"


  # Service section
  [params.services]
    headline = "Our team"
    bio = "Jody has been an elementary school teacher in the San Francisco Unified School District for the past 10 years and is also a [National Board Certified Teacher](//nbpts.org). In addition, she has been performing improv comedy in San Francisco for the past 15 years. Her current troupe, Chicken Scratch, has be a mainstay of the [San Francisco Improv Fest](//sfimprovfestival.com) for the last 6 years."

        [[params.services.list]]
            image = "dawn-headshot-300x300.jpg"
            title = "Dawn Needelman"
            description = "Board Member | Secretary"

        [[params.services.list]]
      image = "shawn-headshot-300x300.jpg"
      title = "Shawn Kresal"
      description = "Board Member | Vice President"

    [[params.services.list]]
            image = "jay-headshot-300x300.jpg"
            title = "Jay Huston"
            description = "Board Member | Curriculum Development"

        [[params.services.list]]
            image = "chris-headshot-300x300.jpg"
            title = "Chris Moradi"
            description = "Board Member | Treasurer"


    # Portfolio modals
  [params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
  [params.aside]
    headline = "Get the Creative Theme for Hugo"

    [params.aside.button]
      text = "Download now"
      link = "//github.com/digitalcraftsman/hugo-creative-theme"

  # Contact section
  [params.contact]
    headline = "Let's Get In Touch!"
    description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
    phone = "123-456-6789"
    email = "feedback@startbootstrap.com"
